In [1]:
import pandas as pd

fund_master = pd.read_csv("../Data/Raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [2]:
fund_master.shape

(40, 15)

In [3]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [4]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [5]:
fund_master.describe(include ="all")

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
count,40.000000,40,40,40,40,40,40,40,40.000000,40.000000,40.0,40.000000,40,40,40
unique,NaN,10,40,2,12,2,34,10,NaN,NaN,NaN,NaN,29,5,9
top,NaN,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2013-01-01,NIFTY 100 TRI,NaN,NaN,NaN,NaN,Sohini Andani,Moderate,EC01
freq,NaN,5,1,34,14,32,7,14,NaN,NaN,NaN,NaN,2,16,14
mean,120247.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.237000,0.812500,500.0,1277.500000,NaN,NaN,NaN
std,14534.998667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.386584,0.387091,0.0,1082.847031,NaN,NaN,NaN
min,100016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.550000,0.000000,500.0,100.000000,NaN,NaN,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.787500,1.000000,500.0,1000.000000,NaN,NaN,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.425000,1.000000,500.0,1000.000000,NaN,NaN,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.540000,1.000000,500.0,1000.000000,NaN,NaN,NaN
max,149324.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.640000,1.000000,500.0,5000.000000,NaN,NaN,NaN

In [7]:
fund_master["launch_date"] = pd.to_datetime(fund_master["launch_date"])
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     datetime64[us]
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: datetime64[us](1), float64(2), int64(3), str(9)
memory usage: 4.8 KB

In [8]:
fund_master.dtypes

amfi_code                      int64
fund_house                       str
scheme_name                      str
category                         str
sub_category                     str
plan                             str
launch_date           datetime64[us]
benchmark                        str
expense_ratio_pct            float64
exit_load_pct                float64
min_sip_amount                 int64
min_lumpsum_amount             int64
fund_manager                     str
risk_category                    str
sebi_category_code               str
dtype: object

In [9]:
print("Fund Houses:")
print(fund_master["fund_house"].unique())

print("\nCategories:")
print(fund_master["category"].unique())

print("\nSub Categories:")
print(fund_master["sub_category"].unique())

print("\nRisk Categories:")
print(fund_master["risk_category"].unique())

Fund Houses:
<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

Categories:
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

Sub Categories:
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

Risk Categories:
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [10]:
print(fund_master["fund_house"].value_counts())
print("\n")
print(fund_master["category"].value_counts())
print("\n")
print(fund_master["risk_category"].value_counts())

fund_house
SBI Mutual Fund             5
HDFC Mutual Fund            5
ICICI Prudential MF         5
Nippon India MF             5
Kotak Mahindra MF           4
Axis Mutual Fund            4
Aditya Birla Sun Life MF    3
UTI Mutual Fund             3
Mirae Asset MF              3
DSP Mutual Fund             3
Name: count, dtype: int64


category
Equity    34
Debt       6
Name: count, dtype: int64


risk_category
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

# Data Quality Summary

- Dataset loaded successfully.
- Total Rows: 40
- Total Columns: 15
- Missing Values: 0
- launch_date converted to datetime.
- Fund Houses: 10
- Categories: Equity, Debt
- Dataset is clean and ready for further analysis

In [3]:
import pandas as pd

nav = pd.read_csv("../Data/Raw/02_nav_history.csv")

nav["date"] = pd.to_datetime(nav["date"])
nav = nav.sort_values(["amfi_code", "date"])
nav = nav.drop_duplicates()
nav = nav[nav["nav"] > 0]

nav.to_csv("../Data/Processed/02_nav_history_cleaned.csv", index=False)

print(nav.head())
print("Rows:", len(nav))

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639
Rows: 46000

In [5]:
aum = pd.read_csv("../Data/Raw/03_aum_by_fund_house.csv")

aum = aum.drop_duplicates()

aum.to_csv("../Data/Processed/03_aum_by_fund_house_cleaned.csv", index=False)

print(aum.head())
print("Rows:", len(aum))

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168
Rows: 90

In [6]:
sip = pd.read_csv("../Data/Raw/04_monthly_sip_inflows.csv")

sip = sip.drop_duplicates()

sip.to_csv("../Data/Processed/04_monthly_sip_inflows_cleaned.csv", index=False)

print(sip.head())
print("Rows:", len(sip))

     month  sip_inflow_crore  active_sip_accounts_crore  \
0  2022-01             11517                       4.91
1  2022-02             11438                       4.93
2  2022-03             12328                       5.09
3  2022-04             11863                       5.48
4  2022-05             12286                       5.55

   new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                   9.10                4.80             NaN
1                   8.20                4.85             NaN
2                  10.50                5.01             NaN
3                   9.52                5.12             NaN
4                   8.10                5.15             NaN
Rows: 48

In [7]:
category = pd.read_csv("../Data/Raw/05_category_inflows.csv")

category = category.drop_duplicates()

category.to_csv("../Data/Processed/05_category_inflows_cleaned.csv", index=False)

print(category.head())
print("Rows:", len(category))

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0
Rows: 144

In [10]:
industry = pd.read_csv("../Data/Raw/06_industry_folio_count.csv")

industry = industry.drop_duplicates()

industry.to_csv("../Data/Processed/06_industry_folio_cleaned_count.csv", index=False)

print(industry.head())
print("Rows:", len(industry))

     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48
Rows: 21

In [11]:
scheme = pd.read_csv("../Data/Raw/07_scheme_performance.csv")

scheme = scheme.drop_duplicates()

scheme.to_csv("../Data/Processed/07_scheme_performance_cleaned.csv", index=False)

print(scheme.head())
print("Rows:", len(scheme))

   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low
Rows: 40

In [12]:
import pandas as pd

investor = pd.read_csv("../Data/Raw/08_investor_transactions.csv")

investor = investor.drop_duplicates()

investor.to_csv("../Data/Processed/08_investor_transactions_cleaned.csv", index=False)

print(investor.head())
print("Rows:", len(investor))

  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending
Rows: 32778

In [13]:
import pandas as pd

portfolio = pd.read_csv("../Data/Raw/09_portfolio_holdings.csv")

portfolio = portfolio.drop_duplicates()

portfolio.to_csv("../Data/Processed/09_portfolio_holdings_cleaned.csv", index=False)

print(portfolio.head())
print("Rows:", len(portfolio))

   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31
Rows: 322

In [14]:
import pandas as pd

benchmark = pd.read_csv("../Data/Raw/10_benchmark_indices.csv")

benchmark = benchmark.drop_duplicates()

benchmark.to_csv("../Data/Processed/10_benchmark_indices_cleaned.csv", index=False)

print(benchmark.head())
print("Rows:", len(benchmark))

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15
Rows: 8050

In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../bluestock_mf.db")

tables = {
    "fund_master": "../Data/Raw/01_fund_master.csv",
    "nav_history": "../Data/Processed/02_nav_history_cleaned.csv",
    "aum_by_fund_house": "../Data/Processed/03_aum_by_fund_house_cleaned.csv",
    "monthly_sip_inflows": "../Data/Processed/04_monthly_sip_inflows_cleaned.csv",
    "category_inflows": "../Data/Processed/05_category_inflows_cleaned.csv",
    "industry_folio_count": "../Data/Processed/06_industry_folio_cleaned_count.csv",
    "scheme_performance": "../Data/Processed/07_scheme_performance_cleaned.csv",
    "investor_transactions": "../Data/Processed/08_investor_transactions_cleaned.csv",
    "portfolio_holdings": "../Data/Processed/09_portfolio_holdings_cleaned.csv",
    "benchmark_indices": "../Data/Processed/10_benchmark_indices_cleaned.csv"
}

for table_name, file_path in tables.items():
    df = pd.read_csv(file_path)
    df.to_sql(table_name, conn, if_exists="replace", index=False)
    print(f"Loaded: {table_name}")

conn.close()

print("✅ SQLite database (bluestock_mf.db) created successfully!")

Loaded: fund_master
Loaded: nav_history
Loaded: aum_by_fund_house
Loaded: monthly_sip_inflows
Loaded: category_inflows
Loaded: industry_folio_count
Loaded: scheme_performance
Loaded: investor_transactions
Loaded: portfolio_holdings
Loaded: benchmark_indices
✅ SQLite database (bluestock_mf.db) created successfully!